### ISSUE TITLE
command to open new wolf session [enhancement]

### ISSUE THREAD

**Issue by Almenon** [Duroktar/Wolf#11]
see https://github.com/Almenon/AREPL-vscode/issues/26 and https://github.com/Almenon/AREPL-vscode/issues/13

```typescript
    let newAreplSession = vscode.commands.registerCommand('extension.newAREPLSession', ()=>{
        Utilities.newUnsavedPythonDoc(Utilities.getHighlightedText())
            .then(createPreviewDoc.bind(this, context));
    });
```

You could use the same code to do a similar feature for wolf.  This would fit in line with your goal of making the 'quokka' of python :P

**Comment by Duroktar** [comment]
Oh awesome! Man, you've been such a help, thank you 💯 I can see all the pieces coming together for a really sweet release. I'm gonna dig into this stuff as soon as I can, I've been busy at work otherwise I would have started something already.

Cheers

**Comment by Almenon** [comment]
welcome :)

**Comment by Duroktar** [comment]
Closing. Thanks again 🍻
