### ISSUE TITLE
Save tempfiles to ${workspaceRoot}/.vscode/wolf/

### ISSUE THREAD

**Issue by Duroktar** [Duroktar/Wolf#15]
Right now they're being saved in the same directory as the traced file. Make a new entry point that passes the dir of the traced script for adding to the path, and a seperate filepath to the tempfile.

**Comment by Almenon** [comment]
Why not save it to the OS tempdirectory?  That way the disposal is taken care of for you.

https://nodejs.org/api/os.html#os_os_tmpdir

**Comment by Duroktar** [comment]
Now there's an interesting idea. That would probably work as well, although I do take care of the cleanup already in the controller. It wouldn't hurt to put it in a tempdir that's cleaned up automatically in case I missed a failure point or 2 (or 3, or 4....)

**Comment by Duroktar** [comment]
Closing as this would probably break relative imports. I'm open to PRs though if someone else manages to tackle it. Otherwise it's just a minor annoyance on the rare occasion the tempfile isn't cleaned up properly.
