### ISSUE TITLE
error not displayed

### ISSUE THREAD

**Issue by Almenon** [Duroktar/Wolf#16]
I'm loving QA so far - it's like 5 minutes of testing compared to the hours it takes to actually solve the problem. soooo much easier :P 

anyways, here's the scenario:
```python
import json

x = json.loads('{x:5}')
# error does not display in line above :/
```

Interestingly the error displays sucessfully when you use the #? macro

Windows 10, python 3.5

**Comment by Duroktar** [comment]
Haha, I'm just loving that there's so much feedback going on; It's awesome sauce. You find good errors and report them very clearly. It's much appreciated!

I'll check this scenario out and see what I can come up with. Thanks!

P.S: v0.3.1 is Live right now, not sure if you picked it up yet

**Comment by Duroktar** [comment]
Fixed in next patch release. (v0.3.2)
