### ISSUE TITLE
does not work with python 3.5

### ISSUE THREAD

**Issue by Almenon** [Duroktar/Wolf#2]
Making it python 3.5 syntax compatible is actually a very easy change:

```python
message = f"EXISTS_ERROR: {filename} doesn't exist" # fails
message = "EXISTS_ERROR: "+filename+" doesn't exist" # works
```
As a sidenote, I think your extension is a great idea.  I was thinking about implementing something like this for [AREPL](https://github.com/Almenon/AREPL-vscode)

**Comment by Duroktar** [comment]
This is awesome, thanks very much! I'll give it all a look over and try to have it all up by the morning. 

Cheers 🍻

**Comment by Duroktar** [comment]
Merged. Thanks again!

**Comment by Almenon** [comment]
One more change necessary:

regex matches are not subscriptable in python 3.5.  Instead you want to use groups.

I'll submit a pull request for this along with some unit tests  :)
