### ISSUE TITLE
wolf fails with newline in string and #?

### ISSUE THREAD

**Issue by Almenon** [Duroktar/Wolf#21]
```python
x = "foo\nfaa" #?
```
error:

> None
  File "<string>", line 1

**Comment by Duroktar** [comment]
See my message on #20, I think this has to do with a more unfortunate issue. Thanks for the report!

**Comment by Duroktar** [comment]
Can't get the coloured separator for the decoration, but at least it doesn't clip new-line characters anymore! I'll close this up but go ahead and open it back up if you wanna suggest something else.

Note: Fixed in v0.3.7, closing.
