### ISSUE TITLE
wolf only displays first line

### ISSUE THREAD

**Issue by Almenon** [Duroktar/Wolf#22]
Wolf should display all the lines seperated by whatever line-end character is being used (ex: \n)

```python
x = "foo\nfaa"
x
```

displays: foo

should display: foo\nfaa (with \n being different color to signify it as a special char)

In fixing this be sure to handle other special end chars like \r or \r\n

Or if you don't want to show multiple lines you could add something to indicate that the output has been truncated, either a message or a short little ...

```python
x = "foo\nfaa" #? foo ...
```

**Comment by Duroktar** [comment]
I think `pprint.pformat` does truncating doesn't it? I'll be sure to look into this one, thanks!

**Comment by Duroktar** [comment]
Closing. See #23. Thanks!
