### ISSUE TITLE
truncation [enhancement]

### ISSUE THREAD

**Issue by Almenon** [Duroktar/Wolf#23]
Wolf should truncate if the content is too long.  

Shouldn't be too hard to fix ~ right before displaying the message you would do something like:

```typescript
// get maxStringLength from settings. 
if(preview.length > maxStringLength){
  preview = preview.slice(0,maxStringLength) + "..."
}
```

The user could still hover over the preview to see the box with the full content

Reasoning; The user may read in a very large file and you dont want to spend a bunch of time writing the contents to the screen

**Comment by Duroktar** [comment]
Closed in v0.3.7! Set the cutoff point with the `wolf.maxLineLength` setting. Thanks again, cheers.
