### ISSUE TITLE
can't launch python in forked repo

### ISSUE THREAD

**Issue by Almenon** [Duroktar/Wolf#26]
Was about to raise an issue with the microsoft python extension and then I realized that you have the python path hardcoded in your user settings XD

I'll parse down the settings to its most basic form and add it to the gitignore so we can maintain our own versions.

(I'll submit a pull request for this)

**Comment by Almenon** [comment]
the line in question:

> "python.pythonPath": "${workspaceFolder}/python_modules/bin/python3",

Was wondering why python was trying to use a nonexistant python_modules folder ... lol

**Comment by Almenon** [comment]
Actually, adding to gitignore wont work.  I did the following

> git update-index --assume-unchanged .vscode/settings.json

https://stackoverflow.com/questions/9794931/keep-file-in-a-git-repo-but-dont-track-changes

**Comment by Almenon** [comment]
a alternate solution would be to just delete settings.json from the repo.  In hindsight that might have been simpler than running git update-index.

**Comment by Duroktar** [comment]
You can do `pip install nip.cli` and then run `nip install` from the project directory and it will all just work. Then you can get the NIP-Scripts Extension and be able to run the tests from a menu in the sidebar!

Maybe I should put this note in the README..

**Comment by Almenon** [comment]
User settings should be up to the user - for example, a user might use nvm (node version manager) instead of nip

**Comment by Almenon** [comment]
Oh i was looking at nip (node env) (instead of nip.cli, py env)  man those
names are confusing

**Comment by Duroktar** [comment]
[Nip Isn't Pip](https://github.com/RopePy/nip)  .. I was feeling clever that day lol

**Comment by Duroktar** [comment]
Feel free to close or leave this one up. I don't know if it may help others having similar issues or not. I put an FAQ tag on it anyways.
