### ISSUE TITLE
wolf fails on pass

### ISSUE THREAD

**Issue by Almenon** [Duroktar/Wolf#28]
```python
def foo():
    pass # wolf outputs error: File "<string>", line 1

foo()
```

**Comment by Almenon** [comment]
it also fails on break

**Comment by Almenon** [comment]
fails on continue too (see previous example, just replace break with continue

**Comment by Duroktar** [comment]
Awesome! Okay man, I'm busy for the next bit but I'll have those fixed up soon as I can after.

Hmm, funny that pass and continue break it.. I've got a mighty cryptic regex that should just ignore those keywords.. 

Anyways, thanks for breaking em up too. Cheers :beers:

**Comment by Almenon** [comment]
yeah... the regex is so long it times out on regex101 XD

https://regex101.com/r/sf6nAH/15

BTW you can break regex up into multiple lines and add comments, like so:

```python
import re

WOLF_MACROS = re.compile(r"""
\w # we want to capture word because bla bla bla
\d # then number because bla bla bla
""", re.VERBOSE) # verbose ignores comments and whitespace
```

(Trey Hunner gave a [talk](https://www.youtube.com/watch?v=W4ReH9IPH-Q) to SD python about this recently)

And at some point you probably want to break some of the regex logic out into functions or seperate it out into multiple regexes.
