### ISSUE TITLE
wolf fails to output in very odd scenario

### ISSUE THREAD

**Issue by Almenon** [Duroktar/Wolf#34]
```python
a = [1,2]
print(a) # ) nothing outputted
```

```python
a = [1,2]
print(a) # but remove paren and it works fine!
```

**Comment by Almenon** [comment]
oh and i should mention no errors logged.

**Comment by Duroktar** [comment]
This one is the regex. Weird though, it shouldn't matter what's after the macro symbol(s). I'll get this one with the others when I make some time for it; been busy this week with work.

Thanks! :beers:
