### ISSUE TITLE
not all necessary packages are included with wolf extension

### ISSUE THREAD

**Issue by Almenon** [Duroktar/Wolf#36]
The hunter package is hardcoded in the extension but without the packages it relies on there is no point in including it.  Hunter has the following dependencies: six, colorama, and fields.  Once those packages are included the wolf experience should be more seamless for new users - no installation necessary.

I'll add the packages and submit a pull request.

Also, not sure if you noticed, but wolf got its [first 5-star review](https://marketplace.visualstudio.com/items?itemName=traBpUkciP.wolf#review-details) on the marketplace! :D 

Congrats! 🎉

**Comment by Duroktar** [comment]
Awesome, thanks! I'll merge this in soon as I can :)
