### ISSUE TITLE
possibility of using wrong pip / pip not in PATH

### ISSUE THREAD

**Issue by Almenon** [Duroktar/Wolf#37]
The user might have the python 2 pip or not have pip in the path at all.  As alex suggested [here](https://github.com/Almenon/birdseye-vscode/issues/17), it's better to use

> python -m pip install whatever

I'll fix it and submit a pull request

**Comment by Duroktar** [comment]
Woohoo! Thank you very much, I've been so busy lately Wolf has kinda fallen off my radar. I apologize. I'll merge this in and push a new release as soon as I can. Thanks a ton @Almenon :100:
