### ISSUE TITLE
timeout decorator fails on windows

### ISSUE THREAD

**Issue by Almenon** [Duroktar/Wolf#4]
STDERR: Traceback (most recent call last):
extension.js:154
  File "C:\dev\Wolf\scripts\wolf.py", line 409, in <module>
    sys.exit(main(sys.argv[1]))
  File "C:\dev\Wolf\scripts\wolf.py", line 78, in new_f
    old = signal.signal(signal.SIGALRM, handler)
AttributeError: module 'signal' has no attribute 'SIGALRM'

windows does not support SIGALRM

**Comment by Duroktar** [comment]
Merged. Thanks very much!
