### ISSUE TITLE
wolf fails with ~

### ISSUE THREAD

**Issue by Almenon** [Duroktar/Wolf#40]
```python
foo = ~0 #? File "<string>", line 1
```

**Comment by Duroktar** [comment]
I'll look into this one, thanks!

**Comment by Duroktar** [comment]
Fixed in v0.4.0

![wolf-issue40](https://user-images.githubusercontent.com/19689932/100300624-d3b8a900-2f6c-11eb-8bcc-5fc8d5447de4.png)
