### ISSUE TITLE
telemetry

### ISSUE THREAD

**Issue by Almenon** [Duroktar/Wolf#42]
Adding telemetry to your extension should be very helpful in determining the amount of users, how frequently your users use your extension, when users use your extension, what errors you have, when the errors happen ,how often errors happen, etc...

I write a guide on adding telemetry to a vscode extension:

https://medium.com/@almenon214/adding-telemetry-to-your-vscode-extension-f3d52d2e573c

**Comment by Duroktar** [comment]
Awesome article 💯 Very cool technology and easy to implement, I'll definitely add this to the big release coming up. Thanks!

**Comment by Duroktar** [comment]
I think I'll leave telemetry out for now. But thanks for the links!
