### ISSUE TITLE
Wolf stops working after numerous attempts at saving file

### ISSUE THREAD

**Issue by SheepDomination** [Duroktar/Wolf#43]
Wolf doesn't appear to work with dictionaries; as well after saving a file numerous times, wolf doesn't work. I can enable wolf numerous times by means of the command palette but it doesn't work ?

Wolf should work after a saving a file, it automatically shows the results of the code, but that isn't the case.

**Comment by Almenon** [comment]
Can you give an example of how wolf fails with dictionaries please?

I tried the following:
```python
a = {'a':2} #?
b = {'b':[1,2]} #?
print(type(a))
print(type(b))
```
and wolf handles it correctly.
