### ISSUE TITLE
How to start extension?

### ISSUE THREAD

**Issue by pleaseonthekeys** [Duroktar/Wolf#48]
Hello,
I see that the command for enabling Wolf on a file is wolf.barkAtCurrentFile; however, I am not clear about where I can run that command. Where can I find that in the instructions?
Thanks,
Lauren

**Comment by Duroktar** [comment]
Hi Lauren! Couple ways to do this ..

First way - Hit F1 to open the command menu and type `Bark` which should bring up the command.

Other way - If you have a python file open in the editor there should be a blue paw in the
upper right corner that you can press to start Wolf. This basically does the same thing but
can be a little easier to find.

I hope you enjoy the extension! Let me know if there's anything else I can help with :)

**Comment by Duroktar** [comment]
Closing for now. Feel free to reopen if you have more questions!
