### ISSUE TITLE
a=1 #? got error

### ISSUE THREAD

**Issue by wuhongyewhy** [Duroktar/Wolf#50]
a = 1 #? works well
a=1 #? got error File "<string>", line1 \n

![image](https://user-images.githubusercontent.com/7631427/99859990-b3839580-2bcc-11eb-936b-f3b37808ccc1.png)

**Comment by Duroktar** [comment]
Good catch. I'm working on an update that should be ready in the next few days that has a fix for this. Thank you!

**Comment by Duroktar** [comment]
This is fixed in the latest release (v0.4.x). Thanks again for the report!

![wolf-issue50](https://user-images.githubusercontent.com/19689932/100320334-6e2de200-2f97-11eb-82d1-48ef3cd68816.png)
