### ISSUE TITLE
Hello from Quokka

### ISSUE THREAD

**Issue by ArtemGovorov** [Duroktar/Wolf#8]
Hey Wolf team,

Very impressive work!

We are doing very similar things in Quokka but for JavaScript. So just wanted to say hi to fellow live editing tool.

**Comment by Duroktar** [comment]
Hey,

Awesome, thanks for that!

Really though, I should be thanking you for Quokka.js, I use it daily. It's absolutely amazing and was an _essential_ source of inspiration for Wolf. I learned about it watching @[mpj](https://github.com/mpj) on his FunFunFunction YouTube channel.

BTW, I'm kinda nerding out right now. This was an awesome message to wake up to (especially after working till 6am last night getting the new version of Wolf ready). Thanks again! You folks rock :100:

Cheers to the Quokka.js team!

ps: If you ever want to collaborate let me know, I've got big dreams for Wolf and just really like helping people so the more reach the better!

pps: May I put an excerpt of your message on my readme? I'd like to create a praises section, and this would be a pretty sweet first addition :)

**Comment by Duroktar** [comment]
> We have been thinking of expanding to other languages outside of JavaScript ecosystem in future, so if you don't mind we may reach you at some point to ask about your experience of making the similar tool for Python. Do you have any plans to commercialise the project at some point, for example by adding Wolf Pro edition like we have in Quokka, or are planning to keep it fully free/OSS?

@ArtemGovorov

Yes for sure, please get a hold of me when that time arrives! I would love to eventually have a PRO edition of Wolf, and I think that Wallaby.js would be an ideal home for it. I have no qualms about close sourcing a PRO Edition, that would only make sense I think.

I know it sounds crazy but I was planning on getting a hold of you folks (once things got stabilized) to talk about the same thing. _So_, you dropping a line first is really awesome and makes me feel like maybe my idea wasn't crazy after all!

Feel free to contact me anytime, my email address is on my profile page [here](https://github.com/Duroktar).

Cheers :clinking_glasses:

**Comment by Almenon** [comment]
> I have no qualms about close sourcing a PRO Edition, that would only make sense I think.

No, don't join the dark side!  Come back to the light side of open source, luke!

But seriously, you deserve some 💰 for developing wolf.  Open source is great and all but working your ass off in the few hours when you are not _also doing a full-time job_ is exhausting.  And when you present it to people online they are either like

> "OMG I LOVE IT" 

or

> "wow this sucks worse than hitler" 

Internet users are wierd...

Although you are closed-source @ArtemGovorov I really do appreciate the free version of quokka :)  Awesome product.
