### ISSUE TITLE
wolf settings do not update instantly

### ISSUE THREAD

**Issue by Almenon** [Duroktar/Wolf#9]
1. Change a setting
2. run wolf
3. wolf is still using old setting

**Comment by Duroktar** [comment]
Yes, I need to fix this. There is a note in the README about it (I think), but either way thank you for reporting. I'll try to have it up by tonight.

Cheers

**Comment by Duroktar** [comment]
Fixed with 954c0df. I'll leave the issue open for a bit though in case you want to suggest any changes to the implementation. 🍻

**Comment by Duroktar** [comment]
Gonna close this one, feel free to open it back up if you had anything to add. Thanks!
